/**
 * recommendationService — deterministic bounded recommendation generation.
 *
 * These recommendations are pre-defined, bounded, and non-authoritative.
 * They are selected based on risk flags — not generated by AI.
 * They are then passed to AI for explanation/contextualization only.
 *
 * All suggestion language is intentionally non-authoritative.
 */

import type { PlanRiskFlags, Recommendation } from './types';

const ALL_RECOMMENDATIONS: Recommendation[] = [
  {
    id: 'delay-retirement',
    suggestion: 'One option to consider is delaying retirement by one or more years.',
    reason: 'Delaying retirement reduces the number of withdrawal years and allows additional asset accumulation.',
    potentialImpact: 'Each year of delay can meaningfully extend plan durability.',
    tradeoff: 'Requires continued employment and may not be feasible depending on health or job situation.',
    applicableWhen: 'earlyDepletionRisk',
  },
  {
    id: 'reduce-withdrawals',
    suggestion: 'This plan may benefit from exploring a modestly lower annual withdrawal amount.',
    reason: 'Reducing annual withdrawals can significantly extend how long the portfolio lasts.',
    potentialImpact: 'Even a 5–10% reduction in annual spending can add several years to plan durability.',
    tradeoff: 'Requires lifestyle adjustments that may affect quality of life goals.',
    applicableWhen: 'earlyDepletionRisk',
  },
  {
    id: 'roth-conversion',
    suggestion: 'It may be worth exploring Roth conversion opportunities in early retirement years.',
    reason: 'Converting tax-deferred assets to Roth during lower-income years can reduce future required minimum distributions and tax burden.',
    potentialImpact: 'Can reduce lifetime taxes and improve plan flexibility in later years.',
    tradeoff: 'Conversions increase taxable income in the conversion year and require careful bracket management.',
    applicableWhen: 'taxInefficiencyRisk',
  },
  {
    id: 'spending-flexibility',
    suggestion: 'Building flexibility into annual spending — a variable withdrawal strategy — is one option to consider.',
    reason: 'Reducing withdrawals during early market downturns can meaningfully reduce sequence-of-returns risk.',
    potentialImpact: 'Variable spending can significantly reduce depletion risk in volatile markets.',
    tradeoff: 'Requires willingness and ability to reduce discretionary spending in downturns.',
    applicableWhen: 'sequenceRisk',
  },
  {
    id: 'healthcare-planning',
    suggestion: 'Dedicated healthcare cost planning may be worth exploring given the cost trajectory shown.',
    reason: 'Healthcare costs are a major and often underestimated retirement expense.',
    potentialImpact: 'Planning for Medicare transitions and potential long-term care needs can improve outcome predictability.',
    tradeoff: 'Requires setting aside additional reserves and may reduce early retirement flexibility.',
    applicableWhen: 'healthcareRisk',
  },
  {
    id: 'consider-downsizing',
    suggestion: 'Downsizing or a housing cost reduction is one option that could release meaningful equity.',
    reason: 'Home equity is often a significant but illiquid asset. Releasing it can fund retirement needs.',
    potentialImpact: 'Can materially improve plan durability if the net equity is substantial.',
    tradeoff: 'Involves transaction costs, lifestyle changes, and timing considerations.',
    applicableWhen: 'earlyDepletionRisk',
  },
  {
    id: 'longevity-planning',
    suggestion: 'It may be worth reviewing whether the current plan horizon is long enough.',
    reason: 'Many retirees outlive their initial projections. Planning to age 90 or 95 is increasingly prudent.',
    potentialImpact: 'Extending the horizon may reveal additional risk that the current plan does not address.',
    tradeoff: 'A longer horizon requires either lower spending or more assets.',
    applicableWhen: 'longevityRisk',
  },
];

/**
 * Select applicable recommendations based on active risk flags.
 * Returns at most 4 recommendations to avoid overwhelming users.
 */
export function selectRecommendations(flags: PlanRiskFlags): Recommendation[] {
  const applicable = ALL_RECOMMENDATIONS.filter(
    (r) => flags[r.applicableWhen as keyof PlanRiskFlags] === true
  );
  // Deduplicate and limit to 4
  const seen = new Set<string>();
  const result: Recommendation[] = [];
  for (const rec of applicable) {
    if (!seen.has(rec.id)) {
      seen.add(rec.id);
      result.push(rec);
    }
    if (result.length >= 4) break;
  }
  return result;
}

/**
 * Format recommendations for inclusion in AI prompt.
 */
export function formatRecommendationsForPrompt(recs: Recommendation[]): string {
  if (recs.length === 0) return 'No specific recommendations flagged.';
  return recs
    .map(
      (r, i) =>
        `${i + 1}. ${r.suggestion}\n   Reason: ${r.reason}\n   Impact: ${r.potentialImpact}\n   Tradeoff: ${r.tradeoff}`
    )
    .join('\n\n');
}
